### ISSUE TITLE
Not able to connect to RabbitMQ with a virtual host configured.

### ISSUE THREAD

**Issue by ashfaqDell** [knative-extensions/eventing-rabbitmq#1216]
**Describe the bug**
I am not able to connect to an external rabbitMQ cluster which is accessible through my C# code. In the external connection string configuration, I have not found a place to provide rabbitMQ virtual host. I think it is mandatory for me to provide that to connect to the external rabbitMQ instance as I have access only to that virtual host. 

 **Expected behavior**
I should see a connection established to rabbitMQ

 **To Reproduce**
1. Create a virtual host in a rabbitMQ cluster
2. Create a user and give that user access to that virtual user
3. Provide connection details in rabbitMQ secret file 
4. Use RabbitMQSource to connect to rabbitMQ by providing the previously created secret.

 **Knative release version**
latest

**Comment by gabo1208** [comment]
Hey @ashfaqDell !! Thank you for catching that detail, you are absolutely right we are missing docs regarding that specially in the Broker side. Here I can tell you where to put it for the RabbitMQ Broker and Source:
For the Source:
```
apiVersion: sources.knative.dev/v1alpha1
kind: RabbitmqSource
metadata:
  name: rabbitmq-source-vhost
  namespace: {{ .namespace }}
spec:
  rabbitmqClusterReference:
    name: rabbitmqc
    namespace: {{ .namespace }}
  rabbitmqResourcesConfig:
    exchangeName: "logs"
    queueName: "test"
    vhost: "test-vhost"
  sink:
    ref:
      apiVersion: v1
      kind: Service
      name: recorder
```

For the Broker it goes in the BrokerConfig resource, and the Trigger uses the same vhost as the Broker:
```
apiVersion: eventing.knative.dev/v1alpha1
kind: RabbitmqBrokerConfig
metadata:
  name: rabbitmq-broker-config
  namespace: {{ .namespace }}
spec:
  vhost: "test-vhost"
  rabbitmqClusterReference:
    name: rabbitmqc
    namespace: {{ .namespace }}
```

And if you want to contribute the docs, you are welcome, if you can't then next week I'll be updating them on this regard. Thanks for the concise Report and use case :)!

**Comment by ashfaqDell** [comment]
**Thank you very much. I will be glad to contribute to the documentation. I have one more question. In the secrets file I am providing something like below.**

apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-secret-credentials
  namespace: test
stringData:  
  username: mydomain\myuser
  password: mypassword
  uri: https://test.com:15672

**And my source is like below**

`apiVersion: sources.knative.dev/v1alpha1
kind: RabbitmqSource
metadata:
  name: rabbitmq-source
  namespace: test
spec:
  rabbitmqClusterReference:
    connectionSecret:
      name: rabbitmq-secret-credentials
       # a secret with your external cluster credentials
  rabbitmqResourcesConfig:    
    exchangeName: "eventing-rabbitmq-source"
    queueName: "eventing-rabbitmq-source"
    vhost: "myHost"
    
  sink:
    ref:
      apiVersion: eventing.knative.dev/v1
      kind: Broker
      name: test
      namespace: default`

**Our rabbitMQ server uses default certs and is on SSL. In my C# code I need to provide URL like below.**

`ConnectionFactory factory = new ConnectionFactory();
factory.UserName = "mydomain\myuser";
factory.Password = "mypassword";
factory.VirtualHost = "myHost";
factory.Uri = new Uri("AMQPS://test.com:8071");
IConnection conn = factory.CreateConnection();`

**This works perfectly fine. But through Knative even after providing the vhost, I am unable to connect. I feel this might be because I need to tell Knative to use AMQPS. Can you suggest me here please.**

**Comment by gabo1208** [comment]
Of that we do have an example, check the: https://github.com/knative-extensions/eventing-rabbitmq/blob/main/samples/external-cluster/200-secret.yaml

tl;dr. Set the `port` field in the connection secret:
```
apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-secret-credentials
  namespace: external-cluster-sample
# This is just a sample, don't use it this way in production
stringData:
  username: $EXTERNAL_RABBITMQ_USERNAME
  password: $EXTERNAL_RABBITMQ_PASSWORD
  uri: $EXTERNAL_RABBITMQ_URI:$HTTP_PORT # # https://example.com:12345, example.com:12345, rabbitmqc.namespace:15672
  port: $AMQP_PORT # 5672 default
```

The `amqps` part is infered from the `https` url
