### ISSUE TITLE
Dispatcher silently loosing connection to RabbitMQ cluster

### ISSUE THREAD

**Issue by lpfann** [knative-extensions/eventing-rabbitmq#1287]
**Describe the bug**
Dispatcher pods in our Knative setup silently lose connection to RabbitMQ. During this issue, RabbitMQ shows no connected clients for that specific queue. Notably, the dispatcher container logs do not display any message before or after the disconnection occurs, making it difficult to trace the root cause. The only workaround currently is to restart the affected pod.

It seems like the process is kind of frozen since i guess normally Go is doing some kind of heartbeat check?

Addendum: The dispatcher still executes retries for already pulled events even in those periods, so it still has connections with the event sinks. It just looses connection to the Rabbit cluster.

**Expected behavior**
The dispatcher pods should maintain a stable connection with RabbitMQ. In case of any issues or disconnections, relevant log messages should be generated to aid in troubleshooting.

**To Reproduce**

Steps to **potentially** reproduce the behavior:
1. Deploy a dispatcher pod using Knative version 1.12.0 or 1.11 (tested on both)
2. Send an event with 1mb payload, that takes an unusually long time to complete in the downstream event sink, potentially exceeding the event timeout.
3. Observe the dispatcher pod losing connection to RabbitMQ without any relevant logs.

I'm not 100% sure about these reproduction steps, but we had this issue appear in that case more often.

**Knative release version**
1.12.0, 1.11.5 (tested)

**Additional context**
This issue seems to be reproducible particularly with events that have a long processing time in the downstream event sink. We are looking for ways to further debug this, including enabling or accessing debug logs, to better understand and resolve the issue.

**Comment by lpfann** [comment]
We noticed that it happens repeatedly when sending very big payloads (8MB).
It always looses connection after the request from the dispatcher to the sink times out after 30 minutes (the setting we use in the trigger).

We also noticed that the dispatcher will continue retrying calls to the sink but it wont keep/reestablish connection to the rabbitmq cluster.

Memory usage is also not extremely high and no OOM errors happen.

This is our trigger:
```
apiVersion: eventing.knative.dev/v1
kind: Trigger
metadata:
  annotations:
    eventing.knative.dev/creator: admin
    eventing.knative.dev/lastModifier: admin
    rabbitmq.eventing.knative.dev/parallelism: '100'
  creationTimestamp: '2023-10-17T12:52:25Z'
  generation: 1
 
status:
  conditions:
    - lastTransitionTime: '2023-11-17T15:23:53Z'
      status: 'True'
      type: BrokerReady
    - lastTransitionTime: '2023-10-17T12:52:44Z'
      status: 'True'
      type: DeadLetterSinkResolved
    - lastTransitionTime: '2023-11-29T05:10:15Z'
      status: 'True'
      type: DependencyReady
    - lastTransitionTime: '2023-11-20T16:35:59Z'
      reason: authentication.oidc feature not yet supported for this Broker class
      status: 'True'
      type: OIDCIdentityCreated
    - lastTransitionTime: '2023-11-29T05:10:15Z'
      status: 'True'
      type: Ready
    - lastTransitionTime: '2023-10-17T12:53:21Z'
      status: 'True'
      type: SubscriberResolved
    - lastTransitionTime: '2023-10-17T12:53:21Z'
      status: 'True'
      type: SubscriptionReady
  deadLetterSinkUri: http://{broker}.{NS}.svc.cluster.local
  observedGeneration: 1
  subscriberUri: >-
    http://{sink_url}
spec:
  broker: {broker}
  delivery:
    backoffDelay: PT5S
    backoffPolicy: linear
    deadLetterSink:
      ref:
        apiVersion: serving.knative.dev/v1
        kind: Service
        name: {sink_name}
        namespace: {sink_ns}
    retry: 360
    timeout: PT30M
  filter:
    attributes:
      type: {queue_name}
  subscriber:
    ref:
      apiVersion: {sink_type}
      kind:{sink_kind}
      name: {sink_name}
      namespace: {sink_ns}

```
