### ISSUE TITLE
CrossNamespaceEventLinks not supported

### ISSUE THREAD

**Issue by eloo-abi** [knative-extensions/eventing-rabbitmq#1539]
**Describe the bug**
I want to use cross namespace event link with the RabbitMQ broker but it looks like it is not implement. 
It also does not check if cross namespace is enabled and thus the errors are not really useful.

I guess the best place where we can see that its not working is here:
https://github.com/knative-extensions/eventing-rabbitmq/blob/main/pkg/reconciler/trigger/controller.go#L160

 **Expected behavior**
- Upstream features are supported
or
- If upstream feature is not supported a proper error message is shown

 **To Reproduce**

- Create a RabbitMQ broker in `knative-system`
- Create a tigger in `default` like this
```
apiVersion: eventing.knative.dev/v1
kind: Trigger
metadata:
  name: event-display-trigger
spec:
  brokerRef:
    apiVersion: eventing.knative.dev/v1
    kind: Broker
    name: rabbitmq
    namespace: knative-system
  filter:
    attributes:
      type: dev.knative.sources.ping
  subscriber:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: event-display
```
- see the following error `Failed to lookup Broker for Trigger{error 26 0  broker.eventing.knative.dev "" not found}`

 **Knative release version**
1.17.3

 **Additional context**
Add any other context about the problem here such as proposed priority
